### ISSUE TITLE
flip which gets rid of tsnok and friends

### ISSUE THREAD

**Issue by ilyakooo0** [ilyakooo0/isoparsec#12]

**Comment by buzden** [comment]
[turn](https://github.com/ilyakooo0/isoparsec/blob/54a5b3b50e5d22382ac74e0644918e40caaf5ca3/src/Control/SemiIso.hs#L76) как раз про это?

**Comment by ilyakooo0** [comment]
Про это. 

Задачу пока не закрывал потому что все `tsnok`и еще есть в коде.
